// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSIZz3svIUSGBYF4vLpE83vSPV5ZzKTD0',
    appId: '1:187855862988:web:fe106719b729a951131669',
    messagingSenderId: '187855862988',
    projectId: 'camerastore-86084',
    authDomain: 'camerastore-86084.firebaseapp.com',
    storageBucket: 'camerastore-86084.appspot.com',
    measurementId: 'G-C64DQ8CBZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_KNSGCrfEQnvdfOTyUEzjLg0mKohvyMk',
    appId: '1:187855862988:android:edc96d7e72532623131669',
    messagingSenderId: '187855862988',
    projectId: 'camerastore-86084',
    storageBucket: 'camerastore-86084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC7ALbwKFBWGZP5q9Kqi9J3XovG_O317M',
    appId: '1:187855862988:ios:bbd6b60eb4da24b4131669',
    messagingSenderId: '187855862988',
    projectId: 'camerastore-86084',
    storageBucket: 'camerastore-86084.appspot.com',
    iosBundleId: 'com.example.camerastore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC7ALbwKFBWGZP5q9Kqi9J3XovG_O317M',
    appId: '1:187855862988:ios:bbd6b60eb4da24b4131669',
    messagingSenderId: '187855862988',
    projectId: 'camerastore-86084',
    storageBucket: 'camerastore-86084.appspot.com',
    iosBundleId: 'com.example.camerastore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSIZz3svIUSGBYF4vLpE83vSPV5ZzKTD0',
    appId: '1:187855862988:web:a3adb2f13c79b820131669',
    messagingSenderId: '187855862988',
    projectId: 'camerastore-86084',
    authDomain: 'camerastore-86084.firebaseapp.com',
    storageBucket: 'camerastore-86084.appspot.com',
    measurementId: 'G-B2CC7N9QFF',
  );
}
